### ISSUE TITLE
Three-robots Pathplanning Failed

### ISSUE THREAD

**Issue by githubzhouzz** [ai-winter/ros_motion_planning_visualizer#17]
Hello. I tried to modify the code however it doesn't have use_config.yaml. How can I realize three-robots pathplanning?
![图片](https://github.com/ai-winter/ros_motion_planning_visualizer/assets/166516058/5e1e5304-cf93-42d5-969f-b67ead32ad49)

**Comment by omigeft** [comment]
We are very sorry, but this repository is still under development. If it doesn't work, it's quite normal. For officially released code, please refer to another repository [ROS Motion Planning](https://github.com/ai-winter/ros_motion_planning). If you still encounter this issue while using that repository, please raise another issue in that repository.
